version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: fitness_app_db
      MYSQL_ROOT_PASSWORD: rootsecret  # Only set this for the root user
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
